report_dir: '/home/artem/Programming/bioinformatics/NPD-QUAST-test/snakemake_test/test_1'
report_name: 'm'
run_tool: 'MAGMa+'
challenges: [Challenge-100]
tool_dir: /home/artem/Programming/bioinformatics/MAGMa-plus

