report_dir: '/home/artem/Programming/bioinformatics/NPD-QUAST-test/snakemake_test/test_decoys_4'
report_name: 'd'
run_tool: 'Dereplicator+'
challenges: [Challenge-093,Challenge-092]
options: ['--pass-to-dereplicate " --num_hits_to_report 10 "', '--min-score 1']
tool_dir: /home/artem/Programming/bioinformatics/molDiscovery-2.6.0-beta-Linux
